### ISSUE TITLE
Erro ao executar o comando pix info

### ISSUE THREAD

**Issue by Mift777** [warleysr/autopix#16]
tentei executar o comando pix info e da esse erro no console 

[20:03:03] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
org.bukkit.command.CommandException: Cannot execute command 'pix' in plugin AutoPix v1.0.12 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading,re:mixin}
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2547) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2397) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.client.CChatMessagePacketMixin,pl:mixin:A}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.client.CChatMessagePacketMixin,pl:mixin:A}
        at net.minecraft.network.PacketThreadUtil.mdbd4b21$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

**Comment by warleysr** [comment]
A segunda linha da mensagem de erro já diz o que é:

*Cannot execute command 'pix' in plugin AutoPix v1.0.12 - **plugin is disabled**.*

O plugin está desativado. No console mostra o motivo dele não ter carregado corretamente.
