### ISSUE TITLE
Erro ao Inicializar (1.7.10)

### ISSUE THREAD

**Issue by Eisenbahn** [warleysr/autopix#19]
Usando 1.0.13

`[23:09:48] [Server thread/ERROR]: Error occurred while enabling AutoPix v1.0.13 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
	at io.github.warleysr.autopix.inventory.InventoryManager.loadItem(InventoryManager.java:167) ~[?:?]
	at io.github.warleysr.autopix.inventory.InventoryManager.createMenuInventory(InventoryManager.java:50) ~[?:?]
	at io.github.warleysr.autopix.AutoPix.onEnable(AutoPix.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.133]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.133]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.133]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.133]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemFlag
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:394) ~[PluginClassLoader.class:1.7.10-1448.133]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1448.133]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
	... 14 more
`

Uso Thermos

**Comment by warleysr** [comment]
O plugin não suporta essa versão, apenas 1.8+. Originalmente era 1.13+ mas a pedidos de alguns reduzi para 1.8, tive que fazer diversas adaptações que demandaram algum esforço. Me passa o link do jar que você usa que vou verificar se é viável adaptar para essa versão.

**Comment by Eisenbahn** [comment]
https://github.com/CrucibleMC/Crucible/releases/download/v5.4/Crucible-1.7.10-5.4.jar
Libraries:
https://github.com/CrucibleMC/Crucible/releases/download/v5.4/libraries.zip

**Comment by warleysr** [comment]
Não consegui executar o servidor. Compilei removendo métodos que são 1.8+. Testa esse jar para ver se funciona.
[AutoPix-v1.0.13-crucible.zip](https://github.com/warleysr/autopix/files/13196949/AutoPix-v1.0.13-crucible.zip)

**Comment by Eisenbahn** [comment]
`[02:11:17] [Server thread/ERROR]: Could not load 'plugins/AutoPix-v1.0.13-crucible.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problem: 
	The type com.avaje.ebean.EbeanServer cannot be resolved. It is indirectly referenced from required type org.bukkit.plugin.java.JavaPlugin

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1448.133]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-1448.133]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.Error: Unresolved compilation problem: 
	The type com.avaje.ebean.EbeanServer cannot be resolved. It is indirectly referenced from required type org.bukkit.plugin.java.JavaPlugin

	at io.github.warleysr.autopix.AutoPix.<init>(AutoPix.java:1) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_221]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1448.133]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1448.133]
	... 11 more
`

Apresentou esse ao iniciar

**Comment by warleysr** [comment]
Recebi esse mesmo erro compilando com o jar que me passou. Depois tento compilar com um jar padrão Spigot na versão 1.7.10.

**Comment by Eisenbahn** [comment]
<3

**Comment by warleysr** [comment]
Foi adicionado suporte a versão 1.7.10 na [v1.0.14](https://github.com/warleysr/autopix/releases/tag/v1.0.14).

**Comment by Eisenbahn** [comment]
Carregou o menu e sem erros, mas o QR gera assim 
![image](https://github.com/warleysr/autopix/assets/2753064/f6653c6a-fe67-4fc3-aa8d-0ffa7e913197)

Tá chegando perto hehe

**Comment by warleysr** [comment]
Isso é um problema do jar que você está usando. Na 1.7.10 com o spigot padrão também tive alguns problemas na renderização, o mapa renderizava por partes, então demorava alguns segundos pra ter a imagem completa. Procurei alguma configuração no **spigot.yml** sobre renderização de mapas mas não achei. Infelizmente não vai dar pra você usar o plugin nesse servidor.

**Comment by Eisenbahn** [comment]
Bele. Dá pra dar um jeito. Se eu criar uma imagem no game com o QR praquele valor, dá pra validar?

**Comment by warleysr** [comment]
Não, porque é preciso criar a ordem e salvar no banco de dados. Talvez fazer com que o jogador compre pelo plugin e explicar para pagar outro QR code ou disponibilizar a chave. 

É possível validar qualquer pix desde que a ordem tenha sido criada pelo plugin, isto é, apareça no **/pix lista** do jogador com o mesmo valor que ele irá enviar por Pix.

**Comment by Eisenbahn** [comment]
Se ele gerar pelo plugin pgto de R$1,15 e eu tiver uma imagem QR nesse valor de R$1,15 na mesma chave, não funcionaria?

**Comment by warleysr** [comment]
Sim, foi o que expliquei. Desde que tenha gerado pelo plugin e pague com o mesmo valor irá funcionar. Casos que irá dar problema:
- Jogador faz o pagamento sem gerar antes pelo plugin
- Envia valor diferente do produto que comprou (mesmo que seja 1 centavo)

E se caso acontecer dele pagar sem gerar pelo plugin, é possível gerar depois e em seguida validar, também funcionaria.

**Comment by Eisenbahn** [comment]
Uma dúvida:
O código do plugin para validar o pix não seria diferente daquele gerado por FORA do plugin?
Bom, vou fazer uns testes

**Comment by Eisenbahn** [comment]
Deu certo como c sugeriu. Valeus
