### ISSUE TITLE
Erro ao gerar QR (1.16.6 Arclight)

### ISSUE THREAD

**Issue by Eisenbahn** [warleysr/autopix#20]
`[23:23:40] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Eisenbahnn issued server command: /autopixmenu
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.mercadopago.com/v1/payments
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.createPixPayment(MercadoPagoAPI.java:57)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at io.github.warleysr.autopix.inventory.InventoryListener$1.run(InventoryListener.java:109)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.mercadopago.MercadoPagoAPI:createPixPayment:88]:    at java.base/java.lang.Thread.run(Thread.java:833)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.mercadopago.com/v1/payments
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]:      at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]:      at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]:      at io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.createPixPayment(MercadoPagoAPI.java:55)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]:      ... 6 more
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]: java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "data" is null
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at io.github.warleysr.autopix.qrcode.ImageCreator.generateQR(ImageCreator.java:31)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at io.github.warleysr.autopix.inventory.InventoryListener$1.run(InventoryListener.java:122)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:23:53] [Craft Scheduler Thread - 5/INFO] [STDERR/]: [io.github.warleysr.autopix.inventory.InventoryListener$1:run:140]:     at java.base/java.lang.Thread.run(Thread.java:833)
`

Inicializou corretamente, gerou arquivos, abriu menu, e na hora de gerar o QR, apresentou este erro acima.

A config está com meu Token, acredito que esteja correta

**Comment by warleysr** [comment]
Não está. Se ver o erro no inicio mostra:
```
HTTP response code: 401
```

Esse erro corresponde a "Não Autorizado".

**Comment by Eisenbahn** [comment]
Uhm.. Seria alguma config incorreta? Desculpe a ignorancia

**Comment by warleysr** [comment]
Sim. No **token-mp** na config deve ficar assim:
`
token-mp: 'APP_USR-...'
`

É o Access Token de produção que você deve copiar.

**Comment by Eisenbahn** [comment]
Certo, parece que funcionou e ele gerou o QR. 

Mas nesse meio tempo:
- Gerei e paguie um QR, infos pareciam ok
- estava no automatico, então não consegui ativar. 
- desativei o automatico, reiniciei
- ativei manualmente, o produto é o padrão da config. não deu o /say da config
- já consta como ativado

- reiniciei, gerei outros QR, mas dessa vez nenhum deles funcionou. os apps dos bancos não estão reconhecendo (quebrei algo?)

**Comment by warleysr** [comment]
Pra descobrir o que pode estar acontecendo preciso de mais informações.

- O que aconteceu quando fez /pix validar \<CODIGO\>? Apareceu a mensagem de validado com sucesso ou algum erro no console?
- A geração dos QRs depende diretamente da configuração correta da chave e do produto. O que você mudou na config entre o momento que gerou o código correto e quando passou a não gerar mais?

**Comment by Eisenbahn** [comment]
- Tentei executar algumas vezes manualmente (quando estava com o Automatico ligado, aí reparei o erro)
- restartei, ai tentei novamente. Errei a digitação. E então só mostrou:
![image](https://github.com/warleysr/autopix/assets/2753064/8709557c-afdd-43d1-a1b0-8ac97a65115f)

- executei de novo e aí mostrou só o Validando Pix e mais NADA

- tentei novamente o código certo e então, constava que já estava Validado

nesse meio tempo não mostrou /say, nem ingame nem no console

----

A geração dos QRs depende diretamente da configuração correta da chave e do produto. O que você mudou na config entre o momento que gerou o código correto e quando passou a não gerar mais?

- cheguei a alterar o arquivo de messages
- troquei de automatico true pra false

**Comment by Eisenbahn** [comment]
- Reiniciei com o Auto LIGADO e o QR reconheceu... :(

**Comment by Eisenbahn** [comment]
Reparei que há diferenças entre os QR do Auto true e Auto false:
![image](https://github.com/warleysr/autopix/assets/2753064/da760d37-4f8a-41c1-a33e-f914a3ce0694)

**Comment by warleysr** [comment]
Acredito que entendi o problema. Simplesmente ativar ou desativar o modo automático não é uma opção. Os modos são completamente diferentes.

- Modo manual: pix com QR code estático (gerado sem a API do MP pela chave cadastrada). Deve ser confirmado manualmente com o comando /pix validar.
- Modo automático: QR code gerado pela API do MP, onde é passado uma URL para receber a confirmação do pagamento.

Então, quando você desativa o modo automático, a chave cadastrada na config tem que estar com o formato correto para o QR ser gerado. Verifica a chave que cadastrou.

No modo automático você tem que configurar o arquivo notification.php e colocar em um site para ser a URL de notificação, se ela estiver incorreta ou não funcionar, ao pagar o pix nada irá acontecer.

**Comment by Eisenbahn** [comment]
Certo
Minha chave está como CPF com Pontos e Hífen. Vou testar só com números

**Comment by Eisenbahn** [comment]
Bom, troquei pra chave aleatória e parece que gerou o QR.

Mas nada de gerar o comando ainda.

![image](https://github.com/warleysr/autopix/assets/2753064/be12828e-4d2f-49de-9b7d-79b5cf956e56)

**Comment by warleysr** [comment]
Só vai executar os comandos quando for validado. Depois da mensagem "validando pix" acontece o quê? Se der erro é pra mostrar no console.

**Comment by Eisenbahn** [comment]
![image](https://github.com/warleysr/autopix/assets/2753064/84e8407a-0417-4d4e-a611-8b79b5cef965)

Ele consta como aprovado, mas nunca mostrou nenhuma outra mensagem após o 'Validando seu PIX'
Nem nunca gerou o comando do produto

**Comment by warleysr** [comment]
Entendi. Tô imaginando que tem um bug na obtenção dos comandos depois que implementei os múltiplos menus. Depois vou dar uma olhada pra confirmar.

**Comment by warleysr** [comment]
Corrigido na versão [v1.0.14](https://github.com/warleysr/autopix/releases/tag/v1.0.14).
