### ISSUE TITLE
ajuda

### ISSUE THREAD

**Issue by BattleMN** [warleysr/autopix#27]
: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mercadopago.com/v1/payments
[11:01:25 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[11:01:25 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[11:01:25 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2055)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2050)
[11:01:25 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2049)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1619)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[11:01:25 WARN]:        at AutoPix-v1.0.18.jar//io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.createPixPayment(MercadoPagoAPI.java:56)
[11:01:25 WARN]:        at AutoPix-v1.0.18.jar//io.github.warleysr.autopix.inventory.InventoryListener$1.run(InventoryListener.java:113)
[11:01:25 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[11:01:25 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:01:25 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:01:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:01:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:01:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:01:25 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mercadopago.com/v1/payments
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[11:01:25 WARN]:        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
[11:01:25 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
[11:01:25 WARN]:        at AutoPix-v1.0.18.jar//io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.createPixPayment(MercadoPagoAPI.java:54)
[11:01:25 WARN]:        ... 7 more
[11:01:25 WARN]: java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "data" is null
[11:01:25 WARN]:        at AutoPix-v1.0.18.jar//io.github.warleysr.autopix.qrcode.ImageCreator.generateQR(ImageCreator.java:31)
[11:01:25 WARN]:        at AutoPix-v1.0.18.jar//io.github.warleysr.autopix.inventory.InventoryListener$1.run(InventoryListener.java:126)
[11:01:25 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[11:01:25 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:01:25 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:01:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:01:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:01:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

queria saber pq o meu fica dando esse erro, to na versão 1.21, poderia ajudar?

**Comment by warleysr** [comment]
Está havendo algum problema na requisição para a API do MercadoPago. Posta sua config aqui para eu analisar (apague alguns caracteres das informações sensíveis).

**Comment by BattleMN** [comment]
![help](https://github.com/user-attachments/assets/008ddce7-9ff6-4d77-a118-3ea2eae06e61)

**Comment by warleysr** [comment]
Se não tem a URL de notificação você tem que usar então o modo manual (definir na config automatico.ativado para false). Dê uma olhada na [Wiki](https://github.com/warleysr/autopix/wiki/Modo-manual) para entender como ele funciona. 

Se sua intenção era usar o modo automático terá que configurar a URL de notificação, também tem na Wiki como faz.

A questão é que ele não gerou o QR (mesmo com a URL não funcionando deveria) então suspeito que tenha algo a mais na config que esteja influenciando a requisição ou a API mudou e é necessário atualizar o plugin.

Posta sua config.yml completa apagando ou mudando alguns caracteres pra eu tentar reproduzir o erro aqui.

**Comment by BattleMN** [comment]
Irmão quando eu dei false na notificação igual vc disse ai foi, agr ta gerando normal, mt obgd!! seu plugin é mt bom, parabéns.
