### ISSUE TITLE
programa n funciona

### ISSUE THREAD

**Issue by patopatetico2** [warleysr/autopix#30]
quando tentamos fazer uma compra pelo /comprar pix em vez de aparecer o pix aparece o codigo abaixo:
[15:41:50 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mercadopago.com/v1/payments
[15:41:50 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[15:41:50 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[15:41:50 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2055)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2050)
[15:41:50 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2049)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1619)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[15:41:50 WARN]:        at AutoPix-v1.0.19.jar//io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.createPixPayment(MercadoPagoAPI.java:56)
[15:41:50 WARN]:        at AutoPix-v1.0.19.jar//io.github.warleysr.autopix.inventory.InventoryListener$1.run(InventoryListener.java:113)
[15:41:50 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:41:50 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:41:50 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:41:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:41:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:41:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[15:41:50 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mercadopago.com/v1/payments
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[15:41:50 WARN]:        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
[15:41:50 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
[15:41:50 WARN]:        at AutoPix-v1.0.19.jar//io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.createPixPayment(MercadoPagoAPI.java:54)
[15:41:50 WARN]:        ... 7 more
[15:41:50 WARN]: java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "data" is null
[15:41:50 WARN]:        at AutoPix-v1.0.19.jar//io.github.warleysr.autopix.qrcode.ImageCreator.generateQR(ImageCreator.java:31)
[15:41:50 WARN]:        at AutoPix-v1.0.19.jar//io.github.warleysr.autopix.inventory.InventoryListener$1.run(InventoryListener.java:126)
[15:41:50 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:41:50 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:41:50 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:41:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:41:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:41:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
e n sabemos oq fazer

**Comment by warleysr** [comment]
Está dando erro ao realizar a requisição pra API do MP. Posta um print da sua config ocultando alguns caracteres para não vazar seus dados aqui.

**Comment by patopatetico2** [comment]
# Token do MercadoPago para consultar transacoes
token-mp: 'APP_USR-7348806767006123-121911-8637b7281a077245207a3312eb03baad-2165522761'

# Configuracoes do PIX
pix:
  # CPF, CNPJ, Celular com +55 e DDD, email ou aleatoria 
  chave: ''
  # Nome do beneficiario com ate 25 caracteres
  nome: ''
  # Ative essa opcao para receber a payload dos codigos gerados
  debug: false
  # Desative essa opcao para nao enviar o mapa para o jogador no modo manual
  mapa: true

# Modo de ativacao automatico
automatico:
  ativado: true
  intervalo: 10
  notificacoes: 'http://meusite.com/autopix/notification.php'
  
# Servidor MySQL para salvamento dos dados
database:
  type: mysql
  db: s22_brpayments
  host: phpmyadmin.redeflow.us
  port: 3306
  user: u22_RPy9IKOMrr
  pass: LhFR37BaEVtKkUPv4K^H^sck

# Tempo de espera para cada acao em segundos
tempos:
  validar: 60
  lista: 30
  criar-pedido: 300

# Mapa de pagamento
mapa:
  nome: '&aQR code de pagamento'
  descricao:
  - '&7Data: &f{data}'
  - '&7Jogador: &f{jogador}'
  - '&7Produto: &f{produto}'
  # Tempo em MINUTOS que o jogador tem
  # para pagar antes que o mapa seja removido
  tempo-pagar: 30
  # Intervalo em SEGUNDOS que a verificacao ira ocorrer
  intervalo: 60
  
# Menus para compra de produtos por PIX
menu:
  principal:
      titulo: '&9&lCompre produtos por &c&lPIX'
      tamanho: 54
      # Lista de produtos disponiveis
      produtos:
        VIP1:
          preco: 0.23
          pre-comandos:
          - 'say {player} gerou uma ordem PIX!'
          comandos:
          - 'say {player} pagou por PIX!'
          icone:
            slot: 5
            material: diamond_sword
            nome: '&6&lVIP 1 &7- &aR${preco}'
            descricao:
            - '&7Vip por &c30 &7dias'
            - '&7Clique para comprar por &aPIX'
  # Menu para confirmar compra
  confirmar:
    titulo: '&9&lConfirmar compra por &c&lPIX'
    tamanho: 27
    cancelar:
      slot: 19
      icone:
        material: wool
        data: 14
        nome: '&cCancelar'
    confirmar:
      slot: 27
      icone:
        material: wool
        data: 5
        nome: '&aConfirmar'
        descricao:
        - '&7Gerar codigo &bQR &7para'
        - '&7pagar por PIX.'
    desconto:
        slot: 14
        icone:
            material: paper
            nome: '&bAplicar cupom'
            descricao:
            - '&7Clique para informar um cupom no chat'

# Cadastrar cupons de desconto
cupons:
    desconto15:
        porcentagem: 15
        # (Opcional, pode ser removida) A validade considera as 0h do dia informado
        validade: 31/12/2023
        itens:
        - vip1
    
# Som ao pagamento ser validado
som:
  ativar: true
  efeito: BLOCK_NOTE_BLOCK_BASS

# Livro de ajuda com instrucoes
info:
  titulo: '&aInfo PIX'
  autor: '&bAutoPix'
  paginas:
    1:
    - ' &2&nPagamentos por PIX&r'
    - ' '
    - '&8Para pagar com &cPIX &8 use o comando:'
    - ' '
    - '      &9/comprarpix'
    - ' '
    - '&8Um menu ira aparecer mostrando os produtos disponiveis.'
    2:
    - '&8Escolha o produto que deseja e ao confirmar sera gerado um &8codigo &4&lQR.'
    - ' '
    - '&8Com o app do seu banco scaneie e realize o pagamento.'
    3:
    - '&8Após finalizar obtenha o ID da transacao.'
    - ' '
    - '&8Ele e mostrado no comprovante, tem &c32 &8caracteres e começa com &8a letra &c&lE&8.'
    - ' '
    - '&8Exemplo:'
    - '&7E00416968202301162037NF2oRtQ73bY'
    4:
    - '&8Com o código em maos digite:'
    - ' '
    - ' &9/pix validar <Codigo>'
    - ' '
    - '&8seu PIX sera validado'
    - '&8e voce receberá seu produto.'




foi ocultado os dados do nome e pix do proprietario mas de resto continua o mesmo da nossa configuracao

**Comment by warleysr** [comment]
@patopatetico2 Deletei seu comentário pois estava expondo suas informações. Aqui todo mundo consegue ver e poderiam pegar seus dados, apagar seu DB etc, tome cuidado. 

O problema era que a API do MercadoPago passou a requerer uma nova chave (`X-Idempotency-Key`) no cabeçalho da requisição. Testei com meu token e dava certo não enviar ela mas com o seu token dava erro, provavelmente ela é necessária para contas mais novas. Corrigi na versão [v1.0.20](https://github.com/warleysr/autopix/releases/tag/v1.0.20), faça o download do novo jar e reinicie o servidor que irá funcionar. Se olhar na sua conta do MP vai ter duas transações que eu criei pra testar 😅.

**Comment by patopatetico2** [comment]
Ok muito obrigado e desculpe o incomodo 😅

Em qui., 19 de dez. de 2024, 21:39, Warley Soares ***@***.***>
escreveu:
