### ISSUE TITLE
Plugin não carrega ao iniciar servidor com java 8

### ISSUE THREAD

**Issue by ServidoresUC** [warleysr/autopix#5]
Olá, tudo bem? Realizamos um teste com o plugin na versão 8 do Java e ele não carregou, exibindo a seguinte mensagem: https://mcpaste.com/f964e3fa436754cc997bc20f07f2d023

Faz ideia de como podemos corrigir essa questão?

**Comment by warleysr** [comment]
Fiz as alterações mas não tive tempo de testar. Pode fazer isso por favor?

[AutoPix-v1.0.8-PRE.zip](https://github.com/warleysr/autopix/files/11502473/AutoPix-v1.0.8-PRE.zip)

**Comment by ServidoresUC** [comment]
Testamos a inicialização e foi normalmente! Muito obrigado. Testarei e caso tenha mais alguma questão te informamos por aqui.

**Comment by ServidoresUC** [comment]
Ao finalizar um pagamento via o modo automático apresentou o seguinte aviso, poderia verificar por gentileza? O QR code do map não foi atualizado com a confirmação.

[14:12:21 WARN]: Unexpected character (<) at position 0.
[14:12:21 WARN]:        at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
[14:12:21 WARN]:        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
[14:12:21 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
[14:12:21 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[14:12:21 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[14:12:21 WARN]:        at io.github.warleysr.autopix.mercadopago.MercadoPagoAPI.getPayment(MercadoPagoAPI.java:112)
[14:12:21 WARN]:        at io.github.warleysr.autopix.OrderManager.validatePendings(OrderManager.java:147)
[14:12:21 WARN]:        at io.github.warleysr.autopix.AutoPix$1.run(AutoPix.java:59)
[14:12:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[14:12:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:12:21 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[14:12:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:12:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:12:21 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by warleysr** [comment]
Vou tentar dar uma olhada. Aparentemente o erro ocorreu ao tentar buscar informações de um pagamento. Os comandos de ativação foram executados? Essa foi a primeira tentativa ou estava validando antes e passou a ocorrer?

**Comment by ServidoresUC** [comment]
Primeira tentativa no modo automático. O comando executado foi o /comprarpix, foi gerado o código, pago, porém não retornou a confirmação. Aí gerou o erro.

**Comment by ServidoresUC** [comment]
https://mcpaste.com/1f59a71f3a99c7a4e020120c698beba2

**Comment by warleysr** [comment]
Ele retornou os dados em XML ao invés de JSON, mas está retornando com os dados do pagamento. Talvez seja algum parâmetro que esqueci de passar na requisição para forçar o retorno em JSON. O estranho é que com minha chave sempre retorna em JSON, vou ver se isso é configurável no MP ou pela URL, vou tentar corrigir hoje.

**Comment by warleysr** [comment]
Na verdade estava retornando o próprio HTML da página e não XML, adicionei um parâmetro no cabeçalho da requisição para informar que a resposta deve ser em JSON. Testa por favor e me fala se resolve.

[AutoPix-v1.0.8-JSON.zip](https://github.com/warleysr/autopix/files/11629302/AutoPix-v1.0.8-JSON.zip)

**Comment by ServidoresUC** [comment]
Funcionou, muito obrigado, @warleysr!

**Comment by ServidoresUC** [comment]
Olá, tudo bem? Seria possível adicionar um sistema de remoção das transações pendentes dentro de 30 minutos feito o pedido? Seria ideal para uma futura atualização para não haver uma sobrecarga na listagem, pois os pedidos acumulam.

**Comment by warleysr** [comment]
@ServidoresUC o que seria a remoção de transações pendentes? Remover do banco de dados? Não ocorre sobrecarga na listagem pois o comando `/pix lista` só mostra as 10 últimas ordens criadas. Tem também um delay configurável que impede que o jogador fique criando ordens muito rapidamente.

Para reportar bug ou sugerir adição de features, crie outro issue para assunto ficar melhor relacionado.
