### ISSUE TITLE
Erro de conexão fechada MySQL

### ISSUE THREAD

**Issue by warleysr** [warleysr/autopix#8]
ele aparentemente tava funcionando, mas depois de um tempo do nada começou a aparecer "ocorreu um erro" quando eu clicava em confirmar pra gerar o qr-code, e começava a floodar essa mensagem no console, eu tenho mais plugins q funcionam com mysql mas só esse que começou a dar isso:

[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1645)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1559)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at AutoPix-v1.0.8-PAPER.jar//io.github.warleysr.autopix.OrderManager.getOrders(OrderManager.java:78)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at AutoPix-v1.0.8-PAPER.jar//io.github.warleysr.autopix.OrderManager.getLastOrder(OrderManager.java:108)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at AutoPix-v1.0.8-PAPER.jar//io.github.warleysr.autopix.AutoPix$2.run(AutoPix.java:70)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor176.newInstance(Unknown Source)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:761)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:564)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1574)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	... 10 more
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[10:50:20] [Craft Scheduler Thread - 1093 - AutoPix/WARN]: 	at java.base/jdk.internal.ref

_Originally posted by @LucasHenriqueDG in https://github.com/warleysr/autopix/issues/7#issuecomment-1584615851_

**Comment by warleysr** [comment]
@LucasHenriqueDG, adicionei uma flag para reconectar automaticamente ao banco caso a conexão seja fechada. Troco o jar e veja se isso resolve o problema.
[AutoPix-v1.0.9.zip](https://github.com/warleysr/autopix/files/11710511/AutoPix-v1.0.9.zip)

**Comment by LucasHenriqueDG** [comment]
esse é o que funciona em paper também?
