### ISSUE TITLE
Erro parser JSON validação manual

### ISSUE THREAD

**Issue by warleysr** [warleysr/autopix#9]
obtive esse erro quando um player tentou usar o comando /pix validar, verifiquei o código e estava correto:

[21:57:47] [Thread-176/WARN]: Unexpected character (<) at position 0.
[21:57:47] [Thread-176/WARN]: 	at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
[21:57:47] [Thread-176/WARN]: 	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
[21:57:47] [Thread-176/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
[21:57:47] [Thread-176/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[21:57:47] [Thread-176/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[21:57:47] [Thread-176/WARN]: 	at AutoPix-v1.0.8-PAPER.jar//io.github.warleysr.autopix.qrcode.MPValidator.validateTransaction(MPValidator.java:57)
[21:57:47] [Thread-176/WARN]: 	at AutoPix-v1.0.8-PAPER.jar//io.github.warleysr.autopix.commands.AutoPixCommand.lambda$0(AutoPixCommand.java:80)
[21:57:47] [Thread-176/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

_Originally posted by @LucasHenriqueDG in https://github.com/warleysr/autopix/issues/7#issuecomment-1585323731_

**Comment by warleysr** [comment]
@LucasHenriqueDG, este erro provavelmente é o mesmo relacionado ao issue https://github.com/warleysr/autopix/issues/5#issuecomment-1568792040. Implementei uma correção pro modo automático mas esqueci de implementar para o modo manual. Implementei nesta versão. Vou fechar o do descontos já que a feature foi implementada, em caso de outros bugs abra outro issue.
[AutoPix-v1.0.10.zip](https://github.com/warleysr/autopix/files/11711179/AutoPix-v1.0.10.zip)
